version: '1.0'
services:
  api:
    container_name: django_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    container_name: django_db
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: db_blog
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql